# Generated by Django 5.0.3 on 2024-03-23 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondTypeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
