# Generated by Django 5.0.3 on 2024-03-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_secondtypeprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondTypeProfile',
        ),
    ]
